name: example
description: A sample command-line application.
version: 1.0.0

publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  ejson_annotation: ^0.4.0

dev_dependencies:
  custom_lint: ^0.8.1
  ejson_lint: ^0.4.0
  lints: ^5.1.1
