name: ejson_lint
description: >-
  Lints for EJSON.

  BSON is a binary format used to store JSON-like documents efficiently.
  EJSON extends JSON defining how all BSON types should be represented in JSON.

version: 0.4.0
repository: https://github.com/realm/realm-dart/ejson/packages/ejson_lint

environment:
  sdk: ^3.7.0

dependencies:
  analyzer: ^8.1.1
  custom_lint_builder: ^0.8.1
  ejson_analyzer: ^0.4.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.9
