name: ejson_analyzer
description: >-
  Common analysis code for EJSON packages.

  BSON is a binary format used to store JSON-like documents efficiently.
  EJSON extends JSON defining how all BSON types should be represented in JSON.

version: 0.4.1
repository: https://github.com/realm/realm-dart/ejson/packages/ejson_analyzer

environment:
  sdk: ^3.7.0

dependencies:
  analyzer: ^8.1.1
  ejson_annotation: ^0.4.1
  source_gen: ^4.0.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.9
